version: 0.2

phases:
  pre_build:
    commands:
      - echo Started pre_build phase...
      # set time zone
      - cp /usr/share/zoneinfo/Asia/Taipei /etc/localtime
      # set the tag of the previous image
      - PREVIOUS_IMAGE_TAG=$(date +%Y%m%d%H%M%S)
      - echo $PREVIOUS_IMAGE_TAG > image_tag.txt
      - ls -al
      - aws --version
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin public.ecr.aws/$ALIAS
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG -f Dockerfile.base .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG public.ecr.aws/$ALIAS/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/$ALIAS/$IMAGE_REPO_NAME:$IMAGE_TAG
      - rm Dockerfile.base
      - ls -al
